name: veterinaria-mascota-dev

services:
  postgres-mascota-dev:
    image: postgres:16-alpine
    container_name: veterinaria-postgres-mascota-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: veterinaria_mascota_db
      POSTGRES_USER: veterinaria
      POSTGRES_PASSWORD: veterinaria
    ports:
      - "15432:5432"
    volumes:
      - veterinaria_mascota_dev_data:/var/lib/postgresql/data

volumes:
  veterinaria_mascota_dev_data: