name: veterinaria-cliente-dev

services:
  postgres-cliente-dev:
    image: postgres:16-alpine
    container_name: veterinaria-postgres-cliente-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: veterinaria_cliente_db
      POSTGRES_USER: veterinaria
      POSTGRES_PASSWORD: veterinaria
    ports:
      - "15436:5432"
    volumes:
      - veterinaria_cliente_dev_data:/var/lib/postgresql/data

volumes:
  veterinaria_cliente_dev_data:
