CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_roles_nombre UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(150) NOT NULL,
    password VARCHAR(100) NOT NULL,
    habilitado BOOLEAN NOT NULL DEFAULT TRUE,
    id_cliente BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT uk_usuarios_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS usuario_roles (
    usuario_id BIGINT NOT NULL,
    rol_id BIGINT NOT NULL,
    PRIMARY KEY (usuario_id, rol_id),
    CONSTRAINT fk_usuario_roles_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_usuario_roles_rol
        FOREIGN KEY (rol_id) REFERENCES roles (id) ON DELETE CASCADE
);

INSERT INTO roles (nombre) VALUES ('ADMIN'), ('CLIENTE');

-- Contrasenas (BCrypt): admin123, cliente123, cliente2123
INSERT INTO usuarios (email, password, habilitado, id_cliente) VALUES
    ('admin@veterinaria.com', '$2a$10$N68dRuS85iYV5bMRkeooH.x.ij6aZAUvlBnCepVIgE7gcgM5XxU6O', TRUE, NULL),
    ('cliente@veterinaria.com', '$2a$10$WHtz2VyBHUnmRDmLBMBQmOE/SUmIPCC1ntp2U5uOoh/Px4fquTnGi', TRUE, 1),
    ('cliente2@veterinaria.com', '$2a$10$tgO84lEGGIR/s.PN54g7vuq59rd2axYnDaNY80mdDG0jhaOFRpK6i', TRUE, 2);

INSERT INTO usuario_roles (usuario_id, rol_id)
SELECT u.id, r.id FROM usuarios u JOIN roles r ON
    (u.email = 'admin@veterinaria.com' AND r.nombre = 'ADMIN')
    OR (u.email IN ('cliente@veterinaria.com', 'cliente2@veterinaria.com') AND r.nombre = 'CLIENTE');
