server:
  port: 18080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: veterinaria-mascota-ms
            uri: lb://veterinaria-mascota-ms
            predicates:
              - Path=/api/v1/mascotas/**,/api/v1/especies/**
          - id: citas-ms
            uri: lb://citas-ms
            predicates:
              - Path=/api/v1/citas/**

logging:
  level:
    pe.edu.upeu.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
