CREATE TABLE IF NOT EXISTS clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    telefono VARCHAR(20),
    direccion VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id),
    CONSTRAINT uk_clientes_email UNIQUE (email)
);

-- Los id coinciden con el claim idCliente que emite veterinaria-auth-ms
INSERT INTO clientes (nombres, apellidos, email, telefono, direccion) VALUES
    ('Ana', 'Quispe Rojas', 'cliente@veterinaria.com', '987654321', 'Av. Los Olivos 123, Lima'),
    ('Luis', 'Mamani Torres', 'cliente2@veterinaria.com', '912345678', 'Jr. Las Flores 456, Juliaca');
